// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"careco/backend/authz"
	"careco/backend/config"
	"careco/backend/config/providers"
	"careco/backend/entrypoint/server"
	"careco/backend/graph"
	"careco/backend/graph/resolver"
	"careco/backend/infra/firestore"
	"careco/backend/infra/gcp"
	"careco/backend/infra/http"
	"careco/backend/log"
	"careco/backend/o11y"
	"careco/backend/web"
	firestore2 "cloud.google.com/go/firestore"
	"context"
)

// Injectors from wire.go:

func build(contextContext context.Context) (*server.Entrypoint, error) {
	output := log.ProvideStdoutOutput()
	environment := config.ProvideEnvironment()
	level := providers.ProvideLogLevel(environment)
	serviceVersion, err := providers.ProvideServiceVersionFromGitRevision(contextContext)
	if err != nil {
		return nil, err
	}
	logger := log.ProvideJSONLogger(output, level, serviceVersion)
	globalInstrumentationToken := log.ProvideGlobalInstrumentation(logger)
	exporter, err := o11y.ProvideSidecarCollectorExporter(contextContext)
	if err != nil {
		return nil, err
	}
	deploymentEnvironmentName := _wireDeploymentEnvironmentNameValue
	resource, err := o11y.ProvideResource(contextContext, serviceVersion, deploymentEnvironmentName)
	if err != nil {
		return nil, err
	}
	tracerProvider, err := o11y.ProvideTracerProvider(contextContext, exporter, resource)
	if err != nil {
		return nil, err
	}
	port := providers.ProvidePort(environment)
	databaseID := _wireDatabaseIDValue
	projectID := _wireProjectIDValue
	emulatorAddr := providers.ProvideFirestoreEmulatorAddr(environment)
	client, err := firestore.ProvideEmulatorClient(contextContext, databaseID, projectID, emulatorAddr, tracerProvider)
	if err != nil {
		return nil, err
	}
	drivingRecordRepository := firestore.ProvideDrivingRecordRepository(tracerProvider, client)
	resolverResolver := resolver.ProvideResolver(drivingRecordRepository, drivingRecordRepository)
	handlerServer := graph.ProvideServer(tracerProvider, resolverResolver)
	issuer, err := providers.ProvideIssuer(environment)
	if err != nil {
		return nil, err
	}
	audience, err := providers.ProvideAudience(environment)
	if err != nil {
		return nil, err
	}
	httpClient := http.ProvideClient(tracerProvider)
	middleware := authz.ProvideMiddleware(issuer, audience, httpClient)
	webServer := web.ProvideServer(port, tracerProvider, handlerServer, middleware)
	entrypoint := server.ProvideEntrypoint(globalInstrumentationToken, tracerProvider, webServer)
	return entrypoint, nil
}

var (
	_wireDeploymentEnvironmentNameValue = o11y.DeploymentEnvironmentName("local")
	_wireDatabaseIDValue                = firestore.DatabaseID(firestore2.DefaultDatabaseID)
	_wireProjectIDValue                 = gcp.ProjectID("dummy")
)
