scalar DateTime

enum Month {
  JANUARY
  FEBRUARY
  MARCH
  APRIL
  MAY
  JUNE
  JULY
  AUGUST
  SEPTEMBER
  OCTOBER
  NOVEMBER
  DECEMBER
}

interface DrivingRecordsConnection {
  nodes: [DailyReport!]!
}

interface DistanceReport {
  odometerValue: Int!
  reportDate: DateTime!
}

type YearlyReport implements DistanceReport {
  year: Int!
  odometerValue: Int!
  monthlyReports: [MonthlyReport!]!
  reportDate: DateTime!
}

type MonthlyReport implements DistanceReport {
  year: Int!
  month: Month!
  odometerValue: Int!
  tripDistance: Int!
  dailyReports: DailyReportsConnection!
  reportDate: DateTime!
}

type DailyReport implements DistanceReport {
  year: Int!
  month: Month!
  day: Int!
  odometerValue: Int!
  tripDistance: Int!
  recordedAt: DateTime!
  memo: String
  reportDate: DateTime!
}

type RecentDrivingRecordsConnection implements DrivingRecordsConnection {
  nodes: [DailyReport!]!
}

type DailyReportsConnection implements DrivingRecordsConnection {
  nodes: [DailyReport!]!
}

type Query {
  recentDrivingRecords(first: Int!): RecentDrivingRecordsConnection!
  yearlyReport(year: Int!): YearlyReport!
  monthlyReport(year: Int!, month: Month!): MonthlyReport!
  lastReport: DailyReport
}

type Mutation {
  recordDrivingRecord(
    date: DateTime!
    odometerValue: Int!
    memo: String
  ): Boolean!
}
