scalar DateTime
scalar Month

type TotalStatistics {
  distanceKilometers: Int!
}

type YearlyReport {
  year: Int!
  distanceKilometers: Int!
  monthlyReports: [MonthlyReport!]!
}

type MonthlyReport {
  year: Int!
  month: Month!
  distanceKilometers: Int!
  dailyReports: [DailyReport!]!
}

type DailyReport {
  year: Int!
  month: Month!
  day: Int!
  distanceKilometers: Int!
  recordedAt: DateTime!
  memo: String
}

type Query {
  totalStatistics: TotalStatistics!
  recentDrivingRecords(first: Int!): [DailyReport!]!
  yearlyReport(year: Int!): YearlyReport!
  monthlyReport(year: Int!, month: Month!): MonthlyReport!
}

type Mutation {
  recordDrivingRecord(
    date: DateTime!
    distanceKilometers: Int!
    memo: String
  ): Boolean!
}
