package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"careco/backend/graph/dtos"
	"careco/backend/graph/exec"
	"context"
	"slices"
	"time"

	"github.com/aereal/iter/seq"
)

func (r *dailyReportResolver) Year(ctx context.Context, obj *dtos.DailyReport) (int, error) {
	return obj.RecordedAt.Year(), nil
}

func (r *dailyReportResolver) Month(ctx context.Context, obj *dtos.DailyReport) (time.Month, error) {
	return obj.RecordedAt.Month(), nil
}

func (r *dailyReportResolver) Day(ctx context.Context, obj *dtos.DailyReport) (int, error) {
	return obj.RecordedAt.Day(), nil
}

func (r *monthlyReportResolver) DistanceKilometers(ctx context.Context, obj *dtos.MonthlyReport) (int, error) {
	var ret int
	for _, dailyReport := range obj.DailyReports {
		ret += dailyReport.DistanceKilometers
	}
	return ret, nil
}

func (r *mutationResolver) RecordDrivingRecord(ctx context.Context, date time.Time, distanceKilometers int, memo *string) (bool, error) {
	return true, nil
}

func (r *queryResolver) TotalStatistics(ctx context.Context) (*dtos.TotalStatistics, error) {
	return &dtos.TotalStatistics{
		DistanceKilometers: 45678,
	}, nil
}

func (r *queryResolver) RecentDrivingRecords(ctx context.Context, first int) ([]*dtos.DailyReport, error) {
	base := time.Date(2025, time.October, 3, 12, 34, 56, 0, time.UTC)
	records := slices.Collect(seq.Take(generateDummyData(base), first))
	return records, nil
}

func (r *queryResolver) YearlyReport(ctx context.Context, year int) (*dtos.YearlyReport, error) {
	yearlyReport := &dtos.YearlyReport{Year: year}
	baseTimes := []time.Time{
		time.Date(year, time.October, 3, 12, 34, 56, 0, time.UTC),
		time.Date(year, time.September, 30, 12, 34, 56, 0, time.UTC),
	}
	for _, baseTime := range baseTimes {
		monthlyReport := &dtos.MonthlyReport{Year: year, Month: baseTime.Month()}
		for dailyReport := range seq.Take(generateDummyData(baseTime), 3) {
			monthlyReport.DailyReports = append(monthlyReport.DailyReports, dailyReport)
		}
		yearlyReport.MonthlyReports = append(yearlyReport.MonthlyReports, monthlyReport)
	}
	return yearlyReport, nil
}

func (r *queryResolver) MonthlyReport(ctx context.Context, year int, month time.Month) (*dtos.MonthlyReport, error) {
	if year != 2025 || month != time.October {
		return nil, errNotImplemented
	}
	base := time.Date(2025, time.October, 3, 12, 34, 56, 0, time.UTC)
	ret := &dtos.MonthlyReport{
		Year:         year,
		Month:        month,
		DailyReports: slices.Collect(seq.Take(generateDummyData(base), 3)),
	}
	return ret, nil
}

func (r *yearlyReportResolver) DistanceKilometers(ctx context.Context, obj *dtos.YearlyReport) (int, error) {
	var ret int
	for _, monthlyReport := range obj.MonthlyReports {
		for _, dailyReport := range monthlyReport.DailyReports {
			ret += dailyReport.DistanceKilometers
		}
	}
	return ret, nil
}

func (r *Resolver) DailyReport() exec.DailyReportResolver { return &dailyReportResolver{r} }

func (r *Resolver) MonthlyReport() exec.MonthlyReportResolver { return &monthlyReportResolver{r} }

func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() exec.QueryResolver { return &queryResolver{r} }

func (r *Resolver) YearlyReport() exec.YearlyReportResolver { return &yearlyReportResolver{r} }

type dailyReportResolver struct{ *Resolver }
type monthlyReportResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type yearlyReportResolver struct{ *Resolver }
