package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"careco/backend/graph/dtos"
	"careco/backend/graph/exec"
	"context"
	"time"
)

func (r *mutationResolver) RecordDrivingRecord(ctx context.Context, date time.Time, distanceKilometers int, memo *string) (bool, error) {
	return false, errNotImplemented
}

func (r *queryResolver) TotalStatistics(ctx context.Context) (*dtos.TotalStatistics, error) {
	return nil, errNotImplemented
}

func (r *queryResolver) RecentDrivingRecords(ctx context.Context, first int) ([]*dtos.DrivingRecord, error) {
	return nil, errNotImplemented
}

func (r *queryResolver) YearlyReport(ctx context.Context, year int) (*dtos.YearlyReport, error) {
	return nil, errNotImplemented
}

func (r *queryResolver) MonthlyReport(ctx context.Context, year int, month time.Month) (*dtos.MonthlyReport, error) {
	return nil, errNotImplemented
}

func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() exec.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
