package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"slices"
	"time"

	"careco/backend/graph/dtos"
	"careco/backend/graph/exec"

	"github.com/aereal/iter/seq"
)

func (r *mutationResolver) RecordDrivingRecord(ctx context.Context, date time.Time, distanceKilometers int, memo *string) (bool, error) {
	return false, errNotImplemented
}

func (r *queryResolver) TotalStatistics(ctx context.Context) (*dtos.TotalStatistics, error) {
	return &dtos.TotalStatistics{
		DistanceKilometers: 45678,
	}, nil
}

func (r *queryResolver) RecentDrivingRecords(ctx context.Context, first int) ([]*dtos.DailyReport, error) {
	base := time.Date(2025, time.October, 3, 12, 34, 56, 0, time.UTC)
	records := slices.Collect(seq.Take(generateDummyData(base), first))
	return records, nil
}

func (r *queryResolver) YearlyReport(ctx context.Context, year int) (*dtos.YearlyReport, error) {
	return nil, errNotImplemented
}

func (r *queryResolver) MonthlyReport(ctx context.Context, year int, month time.Month) (*dtos.MonthlyReport, error) {
	if year != 2025 || month != time.October {
		return nil, errNotImplemented
	}
	base := time.Date(2025, time.October, 3, 12, 34, 56, 0, time.UTC)
	ret := &dtos.MonthlyReport{
		Year:            year,
		Month:           month,
		DailyStatistics: slices.Collect(seq.Take(generateDummyData(base), 3)),
	}
	for _, r := range ret.DailyStatistics {
		ret.DistanceKilometers += r.DistanceKilometers
	}
	return ret, nil
}

func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() exec.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
