// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"careco/backend/authz"
	"careco/backend/cmd/server/internal"
	"careco/backend/config"
	"careco/backend/config/providers"
	"careco/backend/graph"
	"careco/backend/graph/resolver"
	"careco/backend/infra/firestore"
	"careco/backend/infra/http"
	"careco/backend/log"
	"careco/backend/o11y"
	"careco/backend/web"
	"context"
)

// Injectors from wire.go:

func build(contextContext context.Context) (*internal.Entrypoint, error) {
	output := log.ProvideStdoutOutput()
	environment := config.ProvideEnvironment()
	level := providers.ProvideLogLevel(environment)
	serviceVersion, err := providers.ProvideServiceVersion(contextContext, environment)
	if err != nil {
		return nil, err
	}
	logger := log.ProvideJSONLogger(output, level, serviceVersion)
	globalInstrumentationToken := log.ProvideGlobalInstrumentation(logger)
	exporter, err := o11y.ProvideTraceExporter(contextContext)
	if err != nil {
		return nil, err
	}
	deploymentEnvironmentName, err := providers.ProvideDeploymentEnvironmentName(environment)
	if err != nil {
		return nil, err
	}
	resource, err := o11y.ProvideResource(contextContext, serviceVersion, deploymentEnvironmentName)
	if err != nil {
		return nil, err
	}
	tracerProvider, err := o11y.ProvideTracerProvider(contextContext, exporter, resource)
	if err != nil {
		return nil, err
	}
	port := providers.ProvidePort(environment)
	databaseID, err := providers.ProvideFirestoreDatabaseID(environment)
	if err != nil {
		return nil, err
	}
	projectID, err := providers.ProvideGoogleProjectID(environment)
	if err != nil {
		return nil, err
	}
	emulatorAddr := providers.ProvideFirestoreEmulatorAddr(environment)
	client, err := firestore.ProvideClient(contextContext, databaseID, projectID, emulatorAddr, tracerProvider)
	if err != nil {
		return nil, err
	}
	drivingRecordRepository := firestore.ProvideDrivingRecordRepository(tracerProvider, client)
	resolverResolver := resolver.ProvideResolver(drivingRecordRepository, drivingRecordRepository)
	server := graph.ProvideServer(tracerProvider, resolverResolver)
	issuer, err := providers.ProvideIssuer(environment)
	if err != nil {
		return nil, err
	}
	audience, err := providers.ProvideAudience(environment)
	if err != nil {
		return nil, err
	}
	httpClient := http.ProvideClient(tracerProvider)
	middleware, err := authz.ProvideAuth0Middleware(issuer, audience, httpClient)
	if err != nil {
		return nil, err
	}
	webServer := web.ProvideServer(port, tracerProvider, server, middleware)
	entrypoint := internal.ProvideEntrypoint(globalInstrumentationToken, tracerProvider, webServer)
	return entrypoint, nil
}
