// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"careco/backend/cmd/server/internal"
	"careco/backend/config"
	"careco/backend/config/providers"
	"careco/backend/graph"
	"careco/backend/graph/resolver"
	"careco/backend/log"
	"careco/backend/o11y"
	"careco/backend/web"
	"context"
)

// Injectors from wire.go:

func build(contextContext context.Context) (*internal.Entrypoint, error) {
	output := log.ProvideStdoutOutput()
	environment := config.ProvideEnvironment()
	level := providers.ProvideLogLevel(environment)
	serviceVersion, err := providers.ProvideServiceVersionFromGitRevision(contextContext)
	if err != nil {
		return nil, err
	}
	logger := log.ProvideJSONLogger(output, level, serviceVersion)
	globalInstrumentationToken := log.ProvideGlobalInstrumentation(logger)
	deploymentEnvironmentName := _wireDeploymentEnvironmentNameValue
	resource, err := o11y.ProvideResource(contextContext, serviceVersion, deploymentEnvironmentName)
	if err != nil {
		return nil, err
	}
	tracerProvider, err := o11y.ProvideTracerProvider(contextContext, resource)
	if err != nil {
		return nil, err
	}
	port := providers.ProvidePort(environment)
	resolverResolver := resolver.ProvideResolver()
	server := graph.ProvideServer(resolverResolver)
	webServer := web.ProvideServer(port, tracerProvider, server)
	entrypoint := internal.ProvideEntrypoint(globalInstrumentationToken, tracerProvider, webServer)
	return entrypoint, nil
}

var (
	_wireDeploymentEnvironmentNameValue = o11y.DeploymentEnvironmentName("local")
)
