// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"careco/backend/cmd/import-data/internal"
	"careco/backend/config"
	"careco/backend/config/providers"
	"careco/backend/infra/firestore"
	"careco/backend/infra/gcp"
	"careco/backend/log"
	"careco/backend/o11y"
	"careco/backend/usecases/interactions"
	"context"
)

// Injectors from wire.go:

func build(contextContext context.Context) (*internal.Entrypoint, error) {
	output := log.ProvideStdoutOutput()
	environment := config.ProvideEnvironment()
	level := providers.ProvideLogLevel(environment)
	serviceVersion, err := providers.ProvideServiceVersion(contextContext, environment)
	if err != nil {
		return nil, err
	}
	handler := log.ProvideHandler(output, level, serviceVersion)
	logger := log.ProvideJSONLogger(handler)
	globalInstrumentationToken := log.ProvideGlobalInstrumentation(logger)
	exporter, err := o11y.ProvideTraceExporter(contextContext)
	if err != nil {
		return nil, err
	}
	deploymentEnvironmentName := _wireDeploymentEnvironmentNameValue
	resource, err := o11y.ProvideResource(contextContext, serviceVersion, deploymentEnvironmentName)
	if err != nil {
		return nil, err
	}
	tracerProvider, err := o11y.ProvideTracerProvider(contextContext, exporter, resource)
	if err != nil {
		return nil, err
	}
	databaseID, err := providers.ProvideFirestoreDatabaseID(environment)
	if err != nil {
		return nil, err
	}
	projectID := _wireProjectIDValue
	emulatorAddr := providers.ProvideFirestoreEmulatorAddr(environment)
	client, err := firestore.ProvideClient(contextContext, databaseID, projectID, emulatorAddr, tracerProvider)
	if err != nil {
		return nil, err
	}
	drivingRecordRepository := firestore.ProvideDrivingRecordRepository(tracerProvider, client)
	exportFileName, err := providers.ProvideExportFileName(environment)
	if err != nil {
		return nil, err
	}
	importData := interactions.ProvideImportData(tracerProvider, drivingRecordRepository, exportFileName)
	entrypoint := internal.ProvideEntrypoint(globalInstrumentationToken, tracerProvider, importData)
	return entrypoint, nil
}

var (
	_wireDeploymentEnvironmentNameValue = o11y.DeploymentEnvironmentName("local")
	_wireProjectIDValue                 = gcp.ProjectID("dummy")
)
