// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package exec

import (
	"bytes"
	"context"
	"fmt"
	"sync/atomic"
	"time"

	"github.com/99designs/gqlgen/graphql"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	DailyReport() DailyReportResolver
	MonthlyReport() MonthlyReportResolver
	Mutation() MutationResolver
	Query() QueryResolver
	YearlyReport() YearlyReportResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	DailyReport struct {
		Day           func(childComplexity int) int
		Memo          func(childComplexity int) int
		Month         func(childComplexity int) int
		OdometerValue func(childComplexity int) int
		RecordedAt    func(childComplexity int) int
		ReportDate    func(childComplexity int) int
		TripDistance  func(childComplexity int) int
		Year          func(childComplexity int) int
	}

	DailyReportsConnection struct {
		Nodes func(childComplexity int) int
	}

	MonthlyReport struct {
		DailyReports  func(childComplexity int) int
		Month         func(childComplexity int) int
		OdometerValue func(childComplexity int) int
		ReportDate    func(childComplexity int) int
		TripDistance  func(childComplexity int) int
		Year          func(childComplexity int) int
	}

	Mutation struct {
		RecordDrivingRecord func(childComplexity int, date time.Time, odometerValue int, memo *string) int
	}

	Query struct {
		LastReport           func(childComplexity int) int
		MonthlyReport        func(childComplexity int, year int, month time.Month) int
		RecentDrivingRecords func(childComplexity int, first int) int
		YearlyReport         func(childComplexity int, year int) int
	}

	RecentDrivingRecordsConnection struct {
		Nodes func(childComplexity int) int
	}

	YearlyReport struct {
		MonthlyReports func(childComplexity int) int
		OdometerValue  func(childComplexity int) int
		ReportDate     func(childComplexity int) int
		Year           func(childComplexity int) int
	}
}

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "DailyReport.day":
		if e.ComplexityRoot.DailyReport.Day == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.Day(childComplexity), true
	case "DailyReport.memo":
		if e.ComplexityRoot.DailyReport.Memo == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.Memo(childComplexity), true
	case "DailyReport.month":
		if e.ComplexityRoot.DailyReport.Month == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.Month(childComplexity), true
	case "DailyReport.odometerValue":
		if e.ComplexityRoot.DailyReport.OdometerValue == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.OdometerValue(childComplexity), true
	case "DailyReport.recordedAt":
		if e.ComplexityRoot.DailyReport.RecordedAt == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.RecordedAt(childComplexity), true
	case "DailyReport.reportDate":
		if e.ComplexityRoot.DailyReport.ReportDate == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.ReportDate(childComplexity), true
	case "DailyReport.tripDistance":
		if e.ComplexityRoot.DailyReport.TripDistance == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.TripDistance(childComplexity), true
	case "DailyReport.year":
		if e.ComplexityRoot.DailyReport.Year == nil {
			break
		}

		return e.ComplexityRoot.DailyReport.Year(childComplexity), true

	case "DailyReportsConnection.nodes":
		if e.ComplexityRoot.DailyReportsConnection.Nodes == nil {
			break
		}

		return e.ComplexityRoot.DailyReportsConnection.Nodes(childComplexity), true

	case "MonthlyReport.dailyReports":
		if e.ComplexityRoot.MonthlyReport.DailyReports == nil {
			break
		}

		return e.ComplexityRoot.MonthlyReport.DailyReports(childComplexity), true
	case "MonthlyReport.month":
		if e.ComplexityRoot.MonthlyReport.Month == nil {
			break
		}

		return e.ComplexityRoot.MonthlyReport.Month(childComplexity), true
	case "MonthlyReport.odometerValue":
		if e.ComplexityRoot.MonthlyReport.OdometerValue == nil {
			break
		}

		return e.ComplexityRoot.MonthlyReport.OdometerValue(childComplexity), true
	case "MonthlyReport.reportDate":
		if e.ComplexityRoot.MonthlyReport.ReportDate == nil {
			break
		}

		return e.ComplexityRoot.MonthlyReport.ReportDate(childComplexity), true
	case "MonthlyReport.tripDistance":
		if e.ComplexityRoot.MonthlyReport.TripDistance == nil {
			break
		}

		return e.ComplexityRoot.MonthlyReport.TripDistance(childComplexity), true
	case "MonthlyReport.year":
		if e.ComplexityRoot.MonthlyReport.Year == nil {
			break
		}

		return e.ComplexityRoot.MonthlyReport.Year(childComplexity), true

	case "Mutation.recordDrivingRecord":
		if e.ComplexityRoot.Mutation.RecordDrivingRecord == nil {
			break
		}

		args, err := ec.field_Mutation_recordDrivingRecord_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.RecordDrivingRecord(childComplexity, args["date"].(time.Time), args["odometerValue"].(int), args["memo"].(*string)), true

	case "Query.lastReport":
		if e.ComplexityRoot.Query.LastReport == nil {
			break
		}

		return e.ComplexityRoot.Query.LastReport(childComplexity), true
	case "Query.monthlyReport":
		if e.ComplexityRoot.Query.MonthlyReport == nil {
			break
		}

		args, err := ec.field_Query_monthlyReport_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.MonthlyReport(childComplexity, args["year"].(int), args["month"].(time.Month)), true
	case "Query.recentDrivingRecords":
		if e.ComplexityRoot.Query.RecentDrivingRecords == nil {
			break
		}

		args, err := ec.field_Query_recentDrivingRecords_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.RecentDrivingRecords(childComplexity, args["first"].(int)), true
	case "Query.yearlyReport":
		if e.ComplexityRoot.Query.YearlyReport == nil {
			break
		}

		args, err := ec.field_Query_yearlyReport_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.YearlyReport(childComplexity, args["year"].(int)), true

	case "RecentDrivingRecordsConnection.nodes":
		if e.ComplexityRoot.RecentDrivingRecordsConnection.Nodes == nil {
			break
		}

		return e.ComplexityRoot.RecentDrivingRecordsConnection.Nodes(childComplexity), true

	case "YearlyReport.monthlyReports":
		if e.ComplexityRoot.YearlyReport.MonthlyReports == nil {
			break
		}

		return e.ComplexityRoot.YearlyReport.MonthlyReports(childComplexity), true
	case "YearlyReport.odometerValue":
		if e.ComplexityRoot.YearlyReport.OdometerValue == nil {
			break
		}

		return e.ComplexityRoot.YearlyReport.OdometerValue(childComplexity), true
	case "YearlyReport.reportDate":
		if e.ComplexityRoot.YearlyReport.ReportDate == nil {
			break
		}

		return e.ComplexityRoot.YearlyReport.ReportDate(childComplexity), true
	case "YearlyReport.year":
		if e.ComplexityRoot.YearlyReport.Year == nil {
			break
		}

		return e.ComplexityRoot.YearlyReport.Year(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalMap := graphql.BuildUnmarshalerMap()
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

var sources = []*ast.Source{
	{Name: "../../../schema.gql", Input: `scalar DateTime

enum Month {
  JANUARY
  FEBRUARY
  MARCH
  APRIL
  MAY
  JUNE
  JULY
  AUGUST
  SEPTEMBER
  OCTOBER
  NOVEMBER
  DECEMBER
}

interface DrivingRecordsConnection {
  nodes: [DailyReport!]!
}

interface DistanceReport {
  odometerValue: Int!
  reportDate: DateTime!
}

type YearlyReport implements DistanceReport {
  year: Int!
  odometerValue: Int!
  monthlyReports: [MonthlyReport!]!
  reportDate: DateTime!
}

type MonthlyReport implements DistanceReport {
  year: Int!
  month: Month!
  odometerValue: Int!
  tripDistance: Int!
  dailyReports: DailyReportsConnection!
  reportDate: DateTime!
}

type DailyReport implements DistanceReport {
  year: Int!
  month: Month!
  day: Int!
  odometerValue: Int!
  tripDistance: Int!
  recordedAt: DateTime!
  memo: String
  reportDate: DateTime!
}

type RecentDrivingRecordsConnection implements DrivingRecordsConnection {
  nodes: [DailyReport!]!
}

type DailyReportsConnection implements DrivingRecordsConnection {
  nodes: [DailyReport!]!
}

type Query {
  recentDrivingRecords(first: Int!): RecentDrivingRecordsConnection!
  yearlyReport(year: Int!): YearlyReport!
  monthlyReport(year: Int!, month: Month!): MonthlyReport!
  lastReport: DailyReport
}

type Mutation {
  recordDrivingRecord(
    date: DateTime!
    odometerValue: Int!
    memo: String
  ): Boolean!
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// childFields_* functions provide shared child field context lookups.
// Each function is generated once per unique object type, deduplicating the
// switch statements that were previously inlined in every fieldContext_* function.

func (ec *executionContext) childFields_DailyReport(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "year":
		return ec.fieldContext_DailyReport_year(ctx, field)
	case "month":
		return ec.fieldContext_DailyReport_month(ctx, field)
	case "day":
		return ec.fieldContext_DailyReport_day(ctx, field)
	case "odometerValue":
		return ec.fieldContext_DailyReport_odometerValue(ctx, field)
	case "tripDistance":
		return ec.fieldContext_DailyReport_tripDistance(ctx, field)
	case "recordedAt":
		return ec.fieldContext_DailyReport_recordedAt(ctx, field)
	case "memo":
		return ec.fieldContext_DailyReport_memo(ctx, field)
	case "reportDate":
		return ec.fieldContext_DailyReport_reportDate(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type DailyReport", field.Name)
}

func (ec *executionContext) childFields_DailyReportsConnection(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "nodes":
		return ec.fieldContext_DailyReportsConnection_nodes(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type DailyReportsConnection", field.Name)
}

func (ec *executionContext) childFields_MonthlyReport(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "year":
		return ec.fieldContext_MonthlyReport_year(ctx, field)
	case "month":
		return ec.fieldContext_MonthlyReport_month(ctx, field)
	case "odometerValue":
		return ec.fieldContext_MonthlyReport_odometerValue(ctx, field)
	case "tripDistance":
		return ec.fieldContext_MonthlyReport_tripDistance(ctx, field)
	case "dailyReports":
		return ec.fieldContext_MonthlyReport_dailyReports(ctx, field)
	case "reportDate":
		return ec.fieldContext_MonthlyReport_reportDate(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type MonthlyReport", field.Name)
}

func (ec *executionContext) childFields_RecentDrivingRecordsConnection(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "nodes":
		return ec.fieldContext_RecentDrivingRecordsConnection_nodes(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type RecentDrivingRecordsConnection", field.Name)
}

func (ec *executionContext) childFields_YearlyReport(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "year":
		return ec.fieldContext_YearlyReport_year(ctx, field)
	case "odometerValue":
		return ec.fieldContext_YearlyReport_odometerValue(ctx, field)
	case "monthlyReports":
		return ec.fieldContext_YearlyReport_monthlyReports(ctx, field)
	case "reportDate":
		return ec.fieldContext_YearlyReport_reportDate(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type YearlyReport", field.Name)
}

func (ec *executionContext) childFields___Directive(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___Directive_name(ctx, field)
	case "description":
		return ec.fieldContext___Directive_description(ctx, field)
	case "isRepeatable":
		return ec.fieldContext___Directive_isRepeatable(ctx, field)
	case "locations":
		return ec.fieldContext___Directive_locations(ctx, field)
	case "args":
		return ec.fieldContext___Directive_args(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Directive", field.Name)
}

func (ec *executionContext) childFields___EnumValue(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___EnumValue_name(ctx, field)
	case "description":
		return ec.fieldContext___EnumValue_description(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___EnumValue_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___EnumValue_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __EnumValue", field.Name)
}

func (ec *executionContext) childFields___Field(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___Field_name(ctx, field)
	case "description":
		return ec.fieldContext___Field_description(ctx, field)
	case "args":
		return ec.fieldContext___Field_args(ctx, field)
	case "type":
		return ec.fieldContext___Field_type(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___Field_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___Field_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Field", field.Name)
}

func (ec *executionContext) childFields___InputValue(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___InputValue_name(ctx, field)
	case "description":
		return ec.fieldContext___InputValue_description(ctx, field)
	case "type":
		return ec.fieldContext___InputValue_type(ctx, field)
	case "defaultValue":
		return ec.fieldContext___InputValue_defaultValue(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___InputValue_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___InputValue_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __InputValue", field.Name)
}

func (ec *executionContext) childFields___Schema(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "description":
		return ec.fieldContext___Schema_description(ctx, field)
	case "types":
		return ec.fieldContext___Schema_types(ctx, field)
	case "queryType":
		return ec.fieldContext___Schema_queryType(ctx, field)
	case "mutationType":
		return ec.fieldContext___Schema_mutationType(ctx, field)
	case "subscriptionType":
		return ec.fieldContext___Schema_subscriptionType(ctx, field)
	case "directives":
		return ec.fieldContext___Schema_directives(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Schema", field.Name)
}

func (ec *executionContext) childFields___Type(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "kind":
		return ec.fieldContext___Type_kind(ctx, field)
	case "name":
		return ec.fieldContext___Type_name(ctx, field)
	case "description":
		return ec.fieldContext___Type_description(ctx, field)
	case "specifiedByURL":
		return ec.fieldContext___Type_specifiedByURL(ctx, field)
	case "fields":
		return ec.fieldContext___Type_fields(ctx, field)
	case "interfaces":
		return ec.fieldContext___Type_interfaces(ctx, field)
	case "possibleTypes":
		return ec.fieldContext___Type_possibleTypes(ctx, field)
	case "enumValues":
		return ec.fieldContext___Type_enumValues(ctx, field)
	case "inputFields":
		return ec.fieldContext___Type_inputFields(ctx, field)
	case "ofType":
		return ec.fieldContext___Type_ofType(ctx, field)
	case "isOneOf":
		return ec.fieldContext___Type_isOneOf(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Type", field.Name)
}
