// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package exec

import (
	"bytes"
	"context"
	"errors"
	"sync/atomic"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	DailyReport() DailyReportResolver
	MonthlyReport() MonthlyReportResolver
	Mutation() MutationResolver
	Query() QueryResolver
	YearlyReport() YearlyReportResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	DailyReport struct {
		Day                func(childComplexity int) int
		DistanceKilometers func(childComplexity int) int
		Memo               func(childComplexity int) int
		Month              func(childComplexity int) int
		RecordedAt         func(childComplexity int) int
		Year               func(childComplexity int) int
	}

	MonthlyReport struct {
		DailyReports       func(childComplexity int) int
		DistanceKilometers func(childComplexity int) int
		Month              func(childComplexity int) int
		Year               func(childComplexity int) int
	}

	Mutation struct {
		RecordDrivingRecord func(childComplexity int, date time.Time, distanceKilometers int, memo *string) int
	}

	Query struct {
		MonthlyReport        func(childComplexity int, year int, month time.Month) int
		RecentDrivingRecords func(childComplexity int, first int) int
		TotalStatistics      func(childComplexity int) int
		YearlyReport         func(childComplexity int, year int) int
	}

	TotalStatistics struct {
		DistanceKilometers func(childComplexity int) int
	}

	YearlyReport struct {
		DistanceKilometers func(childComplexity int) int
		MonthlyReports     func(childComplexity int) int
		Year               func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "DailyReport.day":
		if e.complexity.DailyReport.Day == nil {
			break
		}

		return e.complexity.DailyReport.Day(childComplexity), true

	case "DailyReport.distanceKilometers":
		if e.complexity.DailyReport.DistanceKilometers == nil {
			break
		}

		return e.complexity.DailyReport.DistanceKilometers(childComplexity), true

	case "DailyReport.memo":
		if e.complexity.DailyReport.Memo == nil {
			break
		}

		return e.complexity.DailyReport.Memo(childComplexity), true

	case "DailyReport.month":
		if e.complexity.DailyReport.Month == nil {
			break
		}

		return e.complexity.DailyReport.Month(childComplexity), true

	case "DailyReport.recordedAt":
		if e.complexity.DailyReport.RecordedAt == nil {
			break
		}

		return e.complexity.DailyReport.RecordedAt(childComplexity), true

	case "DailyReport.year":
		if e.complexity.DailyReport.Year == nil {
			break
		}

		return e.complexity.DailyReport.Year(childComplexity), true

	case "MonthlyReport.dailyReports":
		if e.complexity.MonthlyReport.DailyReports == nil {
			break
		}

		return e.complexity.MonthlyReport.DailyReports(childComplexity), true

	case "MonthlyReport.distanceKilometers":
		if e.complexity.MonthlyReport.DistanceKilometers == nil {
			break
		}

		return e.complexity.MonthlyReport.DistanceKilometers(childComplexity), true

	case "MonthlyReport.month":
		if e.complexity.MonthlyReport.Month == nil {
			break
		}

		return e.complexity.MonthlyReport.Month(childComplexity), true

	case "MonthlyReport.year":
		if e.complexity.MonthlyReport.Year == nil {
			break
		}

		return e.complexity.MonthlyReport.Year(childComplexity), true

	case "Mutation.recordDrivingRecord":
		if e.complexity.Mutation.RecordDrivingRecord == nil {
			break
		}

		args, err := ec.field_Mutation_recordDrivingRecord_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.RecordDrivingRecord(childComplexity, args["date"].(time.Time), args["distanceKilometers"].(int), args["memo"].(*string)), true

	case "Query.monthlyReport":
		if e.complexity.Query.MonthlyReport == nil {
			break
		}

		args, err := ec.field_Query_monthlyReport_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.MonthlyReport(childComplexity, args["year"].(int), args["month"].(time.Month)), true

	case "Query.recentDrivingRecords":
		if e.complexity.Query.RecentDrivingRecords == nil {
			break
		}

		args, err := ec.field_Query_recentDrivingRecords_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.RecentDrivingRecords(childComplexity, args["first"].(int)), true

	case "Query.totalStatistics":
		if e.complexity.Query.TotalStatistics == nil {
			break
		}

		return e.complexity.Query.TotalStatistics(childComplexity), true

	case "Query.yearlyReport":
		if e.complexity.Query.YearlyReport == nil {
			break
		}

		args, err := ec.field_Query_yearlyReport_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.YearlyReport(childComplexity, args["year"].(int)), true

	case "TotalStatistics.distanceKilometers":
		if e.complexity.TotalStatistics.DistanceKilometers == nil {
			break
		}

		return e.complexity.TotalStatistics.DistanceKilometers(childComplexity), true

	case "YearlyReport.distanceKilometers":
		if e.complexity.YearlyReport.DistanceKilometers == nil {
			break
		}

		return e.complexity.YearlyReport.DistanceKilometers(childComplexity), true

	case "YearlyReport.monthlyReports":
		if e.complexity.YearlyReport.MonthlyReports == nil {
			break
		}

		return e.complexity.YearlyReport.MonthlyReports(childComplexity), true

	case "YearlyReport.year":
		if e.complexity.YearlyReport.Year == nil {
			break
		}

		return e.complexity.YearlyReport.Year(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap()
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

var sources = []*ast.Source{
	{Name: "../../../schema.gql", Input: `scalar DateTime
scalar Month

type TotalStatistics {
  distanceKilometers: Int!
}

type YearlyReport {
  year: Int!
  distanceKilometers: Int!
  monthlyReports: [MonthlyReport!]!
}

type MonthlyReport {
  year: Int!
  month: Month!
  distanceKilometers: Int!
  dailyReports: [DailyReport!]!
}

type DailyReport {
  year: Int!
  month: Month!
  day: Int!
  distanceKilometers: Int!
  recordedAt: DateTime!
  memo: String
}

type Query {
  totalStatistics: TotalStatistics!
  recentDrivingRecords(first: Int!): [DailyReport!]!
  yearlyReport(year: Int!): YearlyReport!
  monthlyReport(year: Int!, month: Month!): MonthlyReport!
}

type Mutation {
  recordDrivingRecord(
    date: DateTime!
    distanceKilometers: Int!
    memo: String
  ): Boolean!
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
