// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"careco/backend/config"
	"careco/backend/config/providers"
	"careco/backend/infra/firestore"
	"testing"
)

// Injectors from wire.go:

func BuildDrivingRecordRepository(t *testing.T) (*firestore.DrivingRecordRepository, error) {
	tracerProvider := provideTracerProvider()
	context := provideContext(t)
	databaseID := provideDatabaseID(t)
	projectID := _wireProjectIDValue
	environment := config.ProvideEnvironment()
	emulatorAddr := providers.ProvideFirestoreEmulatorAddr(environment)
	client, err := firestore.ProvideClient(context, databaseID, projectID, emulatorAddr, tracerProvider)
	if err != nil {
		return nil, err
	}
	drivingRecordRepository := firestore.ProvideDrivingRecordRepository(tracerProvider, client, client)
	return drivingRecordRepository, nil
}

var (
	_wireProjectIDValue = firestore.ProjectID("test")
)
