// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"careco/backend/config"
	"careco/backend/infra/firestore"
	"context"
)

// Injectors from wire.go:

func BuildDrivingRecordRepository(contextContext context.Context) (*firestore.DrivingRecordRepository, error) {
	tracerProvider := provideTracerProvider()
	projectID := _wireProjectIDValue
	environment := config.ProvideEnvironment()
	emulatorAddr := provideEmulatorAddr(environment)
	client, err := firestore.ProvideEmulatorClient(contextContext, projectID, emulatorAddr, tracerProvider)
	if err != nil {
		return nil, err
	}
	collectionProvider := provideTestCollectionProvider(client)
	drivingRecordRepository := firestore.ProvideDrivingRecordRepository(tracerProvider, collectionProvider, client)
	return drivingRecordRepository, nil
}

var (
	_wireProjectIDValue = firestore.ProjectID("test")
)
