// Code generated by MockGen. DO NOT EDIT.
// Source: careco/backend/domain (interfaces: DrivingRecordCommand)
//
// Generated by this command:
//
//	mockgen -typed -package mock -destination ./mock_gen.go careco/backend/domain DrivingRecordCommand
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "careco/backend/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDrivingRecordCommand is a mock of DrivingRecordCommand interface.
type MockDrivingRecordCommand struct {
	ctrl     *gomock.Controller
	recorder *MockDrivingRecordCommandMockRecorder
	isgomock struct{}
}

// MockDrivingRecordCommandMockRecorder is the mock recorder for MockDrivingRecordCommand.
type MockDrivingRecordCommandMockRecorder struct {
	mock *MockDrivingRecordCommand
}

// NewMockDrivingRecordCommand creates a new mock instance.
func NewMockDrivingRecordCommand(ctrl *gomock.Controller) *MockDrivingRecordCommand {
	mock := &MockDrivingRecordCommand{ctrl: ctrl}
	mock.recorder = &MockDrivingRecordCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivingRecordCommand) EXPECT() *MockDrivingRecordCommandMockRecorder {
	return m.recorder
}

// RecordDrivingRecord mocks base method.
func (m *MockDrivingRecordCommand) RecordDrivingRecord(ctx context.Context, record *domain.DrivingRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDrivingRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordDrivingRecord indicates an expected call of RecordDrivingRecord.
func (mr *MockDrivingRecordCommandMockRecorder) RecordDrivingRecord(ctx, record any) *MockDrivingRecordCommandRecordDrivingRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDrivingRecord", reflect.TypeOf((*MockDrivingRecordCommand)(nil).RecordDrivingRecord), ctx, record)
	return &MockDrivingRecordCommandRecordDrivingRecordCall{Call: call}
}

// MockDrivingRecordCommandRecordDrivingRecordCall wrap *gomock.Call
type MockDrivingRecordCommandRecordDrivingRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivingRecordCommandRecordDrivingRecordCall) Return(arg0 error) *MockDrivingRecordCommandRecordDrivingRecordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivingRecordCommandRecordDrivingRecordCall) Do(f func(context.Context, *domain.DrivingRecord) error) *MockDrivingRecordCommandRecordDrivingRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivingRecordCommandRecordDrivingRecordCall) DoAndReturn(f func(context.Context, *domain.DrivingRecord) error) *MockDrivingRecordCommandRecordDrivingRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
