// Code generated by MockGen. DO NOT EDIT.
// Source: careco/backend/domain (interfaces: DrivingRecordCommand,DrivingRecordQuery)
//
// Generated by this command:
//
//	mockgen -typed -package mock -destination ./mock_gen.go careco/backend/domain DrivingRecordCommand,DrivingRecordQuery
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "careco/backend/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDrivingRecordCommand is a mock of DrivingRecordCommand interface.
type MockDrivingRecordCommand struct {
	ctrl     *gomock.Controller
	recorder *MockDrivingRecordCommandMockRecorder
	isgomock struct{}
}

// MockDrivingRecordCommandMockRecorder is the mock recorder for MockDrivingRecordCommand.
type MockDrivingRecordCommandMockRecorder struct {
	mock *MockDrivingRecordCommand
}

// NewMockDrivingRecordCommand creates a new mock instance.
func NewMockDrivingRecordCommand(ctrl *gomock.Controller) *MockDrivingRecordCommand {
	mock := &MockDrivingRecordCommand{ctrl: ctrl}
	mock.recorder = &MockDrivingRecordCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivingRecordCommand) EXPECT() *MockDrivingRecordCommandMockRecorder {
	return m.recorder
}

// RecordDrivingRecord mocks base method.
func (m *MockDrivingRecordCommand) RecordDrivingRecord(ctx context.Context, record *domain.DrivingRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDrivingRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordDrivingRecord indicates an expected call of RecordDrivingRecord.
func (mr *MockDrivingRecordCommandMockRecorder) RecordDrivingRecord(ctx, record any) *MockDrivingRecordCommandRecordDrivingRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDrivingRecord", reflect.TypeOf((*MockDrivingRecordCommand)(nil).RecordDrivingRecord), ctx, record)
	return &MockDrivingRecordCommandRecordDrivingRecordCall{Call: call}
}

// MockDrivingRecordCommandRecordDrivingRecordCall wrap *gomock.Call
type MockDrivingRecordCommandRecordDrivingRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivingRecordCommandRecordDrivingRecordCall) Return(arg0 error) *MockDrivingRecordCommandRecordDrivingRecordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivingRecordCommandRecordDrivingRecordCall) Do(f func(context.Context, *domain.DrivingRecord) error) *MockDrivingRecordCommandRecordDrivingRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivingRecordCommandRecordDrivingRecordCall) DoAndReturn(f func(context.Context, *domain.DrivingRecord) error) *MockDrivingRecordCommandRecordDrivingRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDrivingRecordQuery is a mock of DrivingRecordQuery interface.
type MockDrivingRecordQuery struct {
	ctrl     *gomock.Controller
	recorder *MockDrivingRecordQueryMockRecorder
	isgomock struct{}
}

// MockDrivingRecordQueryMockRecorder is the mock recorder for MockDrivingRecordQuery.
type MockDrivingRecordQueryMockRecorder struct {
	mock *MockDrivingRecordQuery
}

// NewMockDrivingRecordQuery creates a new mock instance.
func NewMockDrivingRecordQuery(ctrl *gomock.Controller) *MockDrivingRecordQuery {
	mock := &MockDrivingRecordQuery{ctrl: ctrl}
	mock.recorder = &MockDrivingRecordQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivingRecordQuery) EXPECT() *MockDrivingRecordQueryMockRecorder {
	return m.recorder
}

// CalculateTotalDistance mocks base method.
func (m *MockDrivingRecordQuery) CalculateTotalDistance(ctx context.Context, searchPeriod domain.Interval[time.Time]) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateTotalDistance", ctx, searchPeriod)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateTotalDistance indicates an expected call of CalculateTotalDistance.
func (mr *MockDrivingRecordQueryMockRecorder) CalculateTotalDistance(ctx, searchPeriod any) *MockDrivingRecordQueryCalculateTotalDistanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateTotalDistance", reflect.TypeOf((*MockDrivingRecordQuery)(nil).CalculateTotalDistance), ctx, searchPeriod)
	return &MockDrivingRecordQueryCalculateTotalDistanceCall{Call: call}
}

// MockDrivingRecordQueryCalculateTotalDistanceCall wrap *gomock.Call
type MockDrivingRecordQueryCalculateTotalDistanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivingRecordQueryCalculateTotalDistanceCall) Return(arg0 int64, arg1 error) *MockDrivingRecordQueryCalculateTotalDistanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivingRecordQueryCalculateTotalDistanceCall) Do(f func(context.Context, domain.Interval[time.Time]) (int64, error)) *MockDrivingRecordQueryCalculateTotalDistanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivingRecordQueryCalculateTotalDistanceCall) DoAndReturn(f func(context.Context, domain.Interval[time.Time]) (int64, error)) *MockDrivingRecordQueryCalculateTotalDistanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindRecentRecords mocks base method.
func (m *MockDrivingRecordQuery) FindRecentRecords(ctx context.Context, first int) ([]*domain.DrivingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecentRecords", ctx, first)
	ret0, _ := ret[0].([]*domain.DrivingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecentRecords indicates an expected call of FindRecentRecords.
func (mr *MockDrivingRecordQueryMockRecorder) FindRecentRecords(ctx, first any) *MockDrivingRecordQueryFindRecentRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecentRecords", reflect.TypeOf((*MockDrivingRecordQuery)(nil).FindRecentRecords), ctx, first)
	return &MockDrivingRecordQueryFindRecentRecordsCall{Call: call}
}

// MockDrivingRecordQueryFindRecentRecordsCall wrap *gomock.Call
type MockDrivingRecordQueryFindRecentRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivingRecordQueryFindRecentRecordsCall) Return(arg0 []*domain.DrivingRecord, arg1 error) *MockDrivingRecordQueryFindRecentRecordsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivingRecordQueryFindRecentRecordsCall) Do(f func(context.Context, int) ([]*domain.DrivingRecord, error)) *MockDrivingRecordQueryFindRecentRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivingRecordQueryFindRecentRecordsCall) DoAndReturn(f func(context.Context, int) ([]*domain.DrivingRecord, error)) *MockDrivingRecordQueryFindRecentRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindRecordsInPeriod mocks base method.
func (m *MockDrivingRecordQuery) FindRecordsInPeriod(ctx context.Context, searchPeriod domain.Interval[time.Time]) ([]*domain.DrivingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecordsInPeriod", ctx, searchPeriod)
	ret0, _ := ret[0].([]*domain.DrivingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecordsInPeriod indicates an expected call of FindRecordsInPeriod.
func (mr *MockDrivingRecordQueryMockRecorder) FindRecordsInPeriod(ctx, searchPeriod any) *MockDrivingRecordQueryFindRecordsInPeriodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecordsInPeriod", reflect.TypeOf((*MockDrivingRecordQuery)(nil).FindRecordsInPeriod), ctx, searchPeriod)
	return &MockDrivingRecordQueryFindRecordsInPeriodCall{Call: call}
}

// MockDrivingRecordQueryFindRecordsInPeriodCall wrap *gomock.Call
type MockDrivingRecordQueryFindRecordsInPeriodCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivingRecordQueryFindRecordsInPeriodCall) Return(arg0 []*domain.DrivingRecord, arg1 error) *MockDrivingRecordQueryFindRecordsInPeriodCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivingRecordQueryFindRecordsInPeriodCall) Do(f func(context.Context, domain.Interval[time.Time]) ([]*domain.DrivingRecord, error)) *MockDrivingRecordQueryFindRecordsInPeriodCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivingRecordQueryFindRecordsInPeriodCall) DoAndReturn(f func(context.Context, domain.Interval[time.Time]) ([]*domain.DrivingRecord, error)) *MockDrivingRecordQueryFindRecordsInPeriodCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
