// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dtos

import (
	"time"
)

type DailyReport struct {
	Year               int        `json:"year"`
	Month              time.Month `json:"month"`
	Day                int        `json:"day"`
	DistanceKilometers int        `json:"distanceKilometers"`
}

type DrivingRecord struct {
	RecordedAt         string  `json:"recordedAt"`
	DistanceKilometers int     `json:"distanceKilometers"`
	Memo               *string `json:"memo,omitempty"`
}

type MonthlyReport struct {
	Year               int            `json:"year"`
	Month              time.Month     `json:"month"`
	DistanceKilometers int            `json:"distanceKilometers"`
	DailyStatistics    []*DailyReport `json:"dailyStatistics"`
}

type TotalStatistics struct {
	DistanceKilometers int `json:"distanceKilometers"`
}

type YearlyReport struct {
	Year               int              `json:"year"`
	DistanceKilometers int              `json:"distanceKilometers"`
	MonthlyStatistics  []*MonthlyReport `json:"monthlyStatistics"`
}
