// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dtos

import (
	"time"
)

type DistanceReport interface {
	IsDistanceReport()
}

type DrivingRecordsConnection interface {
	IsDrivingRecordsConnection()
	GetNodes() []*DailyReport
}

type DailyReport struct {
	DistanceKilometers int       `json:"distanceKilometers"`
	RecordedAt         time.Time `json:"recordedAt"`
	Memo               *string   `json:"memo,omitempty"`
}

func (DailyReport) IsDistanceReport() {}

type DailyReportsConnection struct {
	Nodes []*DailyReport `json:"nodes"`
}

func (DailyReportsConnection) IsDrivingRecordsConnection() {}
func (this DailyReportsConnection) GetNodes() []*DailyReport {
	if this.Nodes == nil {
		return nil
	}
	interfaceSlice := make([]*DailyReport, 0, len(this.Nodes))
	for _, concrete := range this.Nodes {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type MonthlyReport struct {
	Year  int        `json:"year"`
	Month time.Month `json:"month"`
}

func (MonthlyReport) IsDistanceReport() {}

type RecentDrivingRecordsConnection struct {
	Nodes []*DailyReport `json:"nodes"`
}

func (RecentDrivingRecordsConnection) IsDrivingRecordsConnection() {}
func (this RecentDrivingRecordsConnection) GetNodes() []*DailyReport {
	if this.Nodes == nil {
		return nil
	}
	interfaceSlice := make([]*DailyReport, 0, len(this.Nodes))
	for _, concrete := range this.Nodes {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type TotalStatistics struct {
	DistanceKilometers int `json:"distanceKilometers"`
}

func (TotalStatistics) IsDistanceReport() {}

type YearlyReport struct {
	Year           int              `json:"year"`
	MonthlyReports []*MonthlyReport `json:"monthlyReports"`
}

func (YearlyReport) IsDistanceReport() {}
