// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"careco/backend/graph"
	"careco/backend/graph/resolver"
	"careco/backend/o11y/test"
)

// Injectors from wire.go:

func BuildHandler() *TestHandler {
	tracerProvider := test.ProvideNoopTracerProvider()
	resolverResolver := resolver.ProvideResolver()
	server := graph.ProvideServer(tracerProvider, resolverResolver)
	testHandler := provideTestServer(server)
	return testHandler
}
