// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"careco/backend/domain/mock"
	"careco/backend/graph"
	"careco/backend/graph/resolver"
	"careco/backend/o11y/test"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

func BuildHandler(controller *gomock.Controller) *TestHandler {
	tracerProvider := test.ProvideNoopTracerProvider()
	mockDrivingRecordCommand := mock.NewMockDrivingRecordCommand(controller)
	mockDrivingRecordQuery := mock.NewMockDrivingRecordQuery(controller)
	resolverResolver := resolver.ProvideResolver(mockDrivingRecordCommand, mockDrivingRecordQuery)
	server := graph.ProvideServer(tracerProvider, resolverResolver)
	testHandler := provideTestServer(server, mockDrivingRecordCommand, mockDrivingRecordQuery)
	return testHandler
}
