---
name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  AQUA_CONFIG: ${{ github.workspace }}/aqua.yaml
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
jobs:
  ok:
    needs:
      - frontend-test
      - frontend-e2e-test
      - frontend-lint
      - frontend-check-diff
      - backend-test
    if: failure()
    permissions: {}
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1
  frontend-test:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          version: v0.73.0
          config: octocov.frontend.yml
  frontend-lint:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.55.2
      - continue-on-error: true
        run: pnpm lint > out.txt
      - env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: reviewdog -f eslint -fail-level any -filter-mode nofilter -reporter github-pr-review < out.txt
  frontend-e2e-test:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    env:
      TZ: Asia/Tokyo
      VITE_AUTH0_DOMAIN: careco.auth0.test
      VITE_AUTH0_CLIENT_ID: dummy-client
      VITE_AUTH0_AUDIENCE: http://careco.test/app
      VITE_AUTH0_ISSUER: https://careco.auth0.test/
      VITE_BACKEND_ENDPOINT: http://localhost:8080/graphql
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - name: generate AUTH0_SECRET
        run: |
          echo "AUTH0_SECRET=$(openssl rand -hex 32)" >> "$GITHUB_ENV"
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium
      - id: test
        continue-on-error: true
        run: pnpm test:e2e
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
      - run: exit 1
        if: ${{ steps.test.outcome == 'failure' }}
  frontend-check-diff:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm codegen
      - run: node ./tools/check-diff.js
  frontend-deploy-preview:
    uses: ./.github/workflows/deploy-vercel.yml
    needs:
      - frontend-check-diff
      - frontend-e2e-test
      - frontend-lint
      - frontend-test
    secrets: inherit
    with:
      environment: preview
  frontend-deploy-production:
    uses: ./.github/workflows/deploy-vercel.yml
    needs:
      - frontend-check-diff
      - frontend-e2e-test
      - frontend-lint
      - frontend-test
    secrets: inherit
    with:
      environment: production
  backend-test:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    services:
      firestore:
        image: 'ghcr.io/aereal/firebase-emulator-image:v0.1.0'
        ports:
          - 8888
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        id: setup-go
        with:
          cache: true
          go-version-file: go.mod
      - run: go mod download
      - name: setup env
        run: |
          echo "FIRESTORE_EMULATOR_ADDR=localhost:${firestore_emulator_port}" >> "$GITHUB_ENV"
        env:
          firestore_emulator_port: ${{ job.services.firestore.ports['8888'] }}
      - name: go test
        run: go test -coverpkg=./... -coverprofile=./coverage.out -timeout=30s ./backend/...
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          version: v0.73.0
          config: octocov.backend.yml
  backend-build:
    runs-on: ubuntu-24.04
    needs:
      - backend-test
    permissions:
      contents: read
      id-token: write
    env:
      REGISTRY: asia-northeast1-docker.pkg.dev
      KOCACHE: ${{ github.workspace }}/.ko-cache
    outputs:
      image: ${{ steps.build.outputs.image }}
      revision: ${{ steps.build.outputs.revision }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        with:
          version: v0.18.0
      - id: auth
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.GCP_PROVIDER_ID }}'
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' # v3.0.1
        with:
          version: '548.0.0'
      - name: configure docker authz
        run: gcloud auth configure-docker "$REGISTRY"
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        id: setup-go
        with:
          cache: true
          go-version-file: go.mod
      - run: go mod download
      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ${{ env.KOCACHE }}
          key: ${{ runner.os }}-ko-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-ko-
      - id: build
        name: build
        run: |
          image="$(ko build --bare --platform linux/amd64 --tags "$image_tag" ./backend/cmd/server)"
          echo "image=${image}" >> "$GITHUB_OUTPUT"
          echo "revision=${image_tag}" >> "$GITHUB_OUTPUT"
        env:
          image_tag: ${{ github.sha }}
          KO_DOCKER_REPO: ${{ env.REGISTRY }}/${{ steps.auth.outputs.project_id }}/backend/backend
  backend-deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    needs:
      - backend-build
    environment:
      name: production-backend
    concurrency:
      group: ${{ github.job }}-${{ github.head_ref }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - id: auth
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.GCP_PROVIDER_ID }}'
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' # v3.0.1
        with:
          version: '548.0.0'
      - uses: google-github-actions/deploy-cloudrun@2028e2d7d30a78c6910e0632e48dd561b064884d # v3.0.1
        with:
          service: production-backend
          image: ${{ needs.backend-build.outputs.image }}
          region: asia-northeast1
          env_vars: |-
            AUTH0_AUDIENCE=https://aereal.org/#careco-dev
            AUTH0_ISSUER=https://careco-dev.jp.auth0.com/
            GOOGLE_CLOUD_PROJECT=${{ steps.auth.outputs.project_id }}
            OTEL_SERVICE_VERSION=${{ needs.backend-build.outputs.revision }}
            FIRESTORE_DATABASE_ID=driving-records
          secrets: |
            ALLOWED_SUBJECTS=allowed_subjects:latest
          flags: |
            --service-account cloud-run-runner@careco-477008.iam.gserviceaccount.com
          labels: |-
            github-head-ref=${{ github.head_ref }}
            github-job=${{ github.job }}
            github-run-id=${{ github.run_id }}
            github-run-number=${{ github.run_number }}
            github-run-attempt=${{ github.run_attempt }}
            github-sha=${{ github.sha }}
